name: satpy
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - affine=2.3.0=py_0
  - aggdraw=1.3.11=py37hdf465ad_2
  - alabaster=0.7.12=py_0
  - appdirs=1.4.3=py_1
  - argh=0.26.2=py37_1001
  - asciitree=0.3.3=py_2
  - astroid=2.4.2=py37hc8dfbb8_0
  - atomicwrites=1.4.0=pyh9f0ad1d_0
  - attrs=19.3.0=py_0
  - autopep8=1.5.3=pyh9f0ad1d_0
  - babel=2.8.0=py_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - bleach=3.1.5=pyh9f0ad1d_0
  - bokeh=2.1.1=py37hc8dfbb8_0
  - boost-cpp=1.72.0=h8e57a91_0
  - brotlipy=0.7.0=py37h8f50634_1000
  - bzip2=1.0.8=h516909a_2
  - ca-certificates=2020.6.20=hecda079_0
  - cairo=1.16.0=hcf35c78_1003
  - cartopy=0.18.0=py37h4b180d9_0
  - certifi=2020.6.20=py37hc8dfbb8_0
  - cffi=1.14.0=py37hd463f26_0
  - cfitsio=3.470=h3eac812_5
  - cftime=1.2.0=py37h03ebfcd_1
  - chardet=3.0.4=py37hc8dfbb8_1006
  - click=7.1.2=pyh9f0ad1d_0
  - click-plugins=1.1.1=py_0
  - cligj=0.5.0=py_0
  - cloudpickle=1.5.0=py_0
  - colorcet=2.0.1=py_0
  - configobj=5.0.6=py_0
  - cryptography=2.9.2=py37hb09aad4_0
  - curl=7.71.1=he644dc0_1
  - cycler=0.10.0=py_2
  - cytoolz=0.10.1=py37h516909a_0
  - dask=2.20.0=py_0
  - dask-core=2.20.0=py_0
  - datashader=0.11.0=pyh9f0ad1d_0
  - datashape=0.5.4=py_1
  - dbus=1.13.6=he372182_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - diff-match-patch=20181111=py_0
  - distributed=2.20.0=py37hc8dfbb8_0
  - docutils=0.16=py37hc8dfbb8_1
  - entrypoints=0.3=py37hc8dfbb8_1001
  - expat=2.2.9=he1b5a44_2
  - fasteners=0.14.1=py_3
  - ffmpeg=4.3=h167e202_0
  - fiona=1.8.13=py37h0492a4a_1
  - flake8=3.8.3=py_1
  - fontconfig=2.13.1=h86ecdb6_1001
  - freetype=2.10.2=he06d7ca_0
  - freexl=1.0.5=h14c3975_1002
  - fsspec=0.7.4=py_0
  - future=0.18.2=py37hc8dfbb8_1
  - gdal=3.0.4=py37h4b180d9_10
  - geopandas=0.8.0=py_1
  - geos=3.8.1=he1b5a44_0
  - geotiff=1.6.0=h05acad5_0
  - geoviews=1.8.1=py_0
  - geoviews-core=1.8.1=py_0
  - gettext=0.19.8.1=hc5be6a0_1002
  - giflib=5.2.1=h516909a_2
  - glib=2.65.0=h6f030ca_0
  - gmp=6.2.0=he1b5a44_2
  - gnutls=3.6.13=h79a8f9a_0
  - gst-plugins-base=1.14.5=h0935bb2_2
  - gstreamer=1.14.5=h36ae1b5_2
  - h5py=2.10.0=nompi_py37h90cd8ad_103
  - hdf4=4.2.13=hf30be14_1003
  - hdf5=1.10.6=nompi_h3c11f04_100
  - heapdict=1.0.1=py_0
  - holoviews=1.13.3=pyh9f0ad1d_0
  - icu=64.2=he1b5a44_1
  - idna=2.10=pyh9f0ad1d_0
  - imageio=2.9.0=py_0
  - imageio-ffmpeg=0.4.2=py_0
  - imagesize=1.2.0=py_0
  - importlib-metadata=1.7.0=py37hc8dfbb8_0
  - importlib_metadata=1.7.0=0
  - intervaltree=3.0.2=py_0
  - ipykernel=5.3.2=py37h43977f1_0
  - ipython=7.16.1=py37h43977f1_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.5.1=py_0
  - isort=4.3.21=py37hc8dfbb8_1
  - jedi=0.17.1=py37hc8dfbb8_0
  - jeepney=0.4.3=py_0
  - jinja2=2.11.2=pyh9f0ad1d_0
  - jpeg=9d=h516909a_0
  - json-c=0.13.1=hbfbb72e_1002
  - jsonschema=3.2.0=py37hc8dfbb8_1
  - jupyter=1.0.0=py_2
  - jupyter_client=6.1.5=py_0
  - jupyter_console=6.1.0=py_1
  - jupyter_core=4.6.3=py37hc8dfbb8_1
  - kealib=1.4.13=h33137a7_1
  - keyring=21.2.1=py37hc8dfbb8_0
  - kiwisolver=1.2.0=py37h99015e2_0
  - krb5=1.17.1=hfafb76e_1
  - lame=3.100=h14c3975_1001
  - lazy-object-proxy=1.4.3=py37h8f50634_2
  - lcms2=2.11=hbd6801e_0
  - ld_impl_linux-64=2.34=h53a641e_7
  - libblas=3.8.0=17_openblas
  - libcblas=3.8.0=17_openblas
  - libclang=9.0.1=default_hde54327_0
  - libcurl=7.71.1=hcdd3856_1
  - libdap4=3.20.6=h1d1bd15_0
  - libedit=3.1.20191231=h46ee950_1
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-ng=9.2.0=h24d8f2e_2
  - libgdal=3.0.4=he6a97d6_10
  - libgfortran-ng=7.5.0=hdf63c60_6
  - libiconv=1.15=h516909a_1006
  - libkml=1.3.0=hb574062_1011
  - liblapack=3.8.0=17_openblas
  - libllvm9=9.0.1=he513fc3_1
  - libnetcdf=4.7.4=nompi_h84807e1_105
  - libopenblas=0.3.10=h5ec1e0e_0
  - libpng=1.6.37=hed695b0_1
  - libpq=12.2=h5513abc_1
  - libsodium=1.0.17=h516909a_0
  - libspatialindex=1.9.3=he1b5a44_3
  - libspatialite=4.3.0a=h2482549_1038
  - libssh2=1.9.0=hab1572f_3
  - libstdcxx-ng=9.2.0=hdf63c60_2
  - libtiff=4.1.0=hc7e4089_6
  - libuuid=2.32.1=h14c3975_1000
  - libwebp-base=1.1.0=h516909a_3
  - libxcb=1.13=h14c3975_1002
  - libxkbcommon=0.10.0=he1b5a44_0
  - libxml2=2.9.10=hee79883_0
  - llvm-openmp=10.0.0=hc9558a2_0
  - llvmlite=0.31.0=py37hd408876_0
  - locket=0.2.0=py_2
  - lz4-c=1.9.2=he1b5a44_1
  - markdown=3.2.2=py_0
  - markupsafe=1.1.1=py37h8f50634_1
  - matplotlib=3.2.2=1
  - matplotlib-base=3.2.2=py37h30547a4_0
  - mccabe=0.6.1=py_1
  - mistune=0.8.4=py37h8f50634_1001
  - monotonic=1.5=py_0
  - msgpack-python=1.0.0=py37h99015e2_1
  - multipledispatch=0.6.0=py_0
  - munch=2.5.0=py_0
  - nbconvert=5.6.1=py37hc8dfbb8_1
  - nbformat=5.0.7=py_0
  - ncurses=6.1=hf484d3e_1002
  - netcdf4=1.5.3=nompi_py37hdc49583_105
  - nettle=3.4.1=h1bed415_1002
  - notebook=6.0.3=py37hc8dfbb8_1
  - nspr=4.26=he1b5a44_0
  - nss=3.47=he751ad9_0
  - numba=0.48.0=py37hb3f55d8_0
  - numcodecs=0.6.4=py37he1b5a44_0
  - numpy=1.18.5=py37h8960a57_0
  - numpydoc=1.1.0=pyh9f0ad1d_0
  - olefile=0.46=py_0
  - openh264=2.1.1=h8b12597_0
  - openjpeg=2.3.1=h981e76c_3
  - openssl=1.1.1g=h516909a_1
  - owslib=0.20.0=py_0
  - packaging=20.4=pyh9f0ad1d_0
  - pandas=1.0.5=py37h0da4684_0
  - pandoc=2.10=0
  - pandocfilters=1.4.2=py_1
  - panel=0.9.7=py_0
  - param=1.9.3=py_0
  - parso=0.7.0=pyh9f0ad1d_0
  - partd=1.1.0=py_0
  - pathtools=0.1.2=py_1
  - pcre=8.44=he1b5a44_0
  - pexpect=4.8.0=py37hc8dfbb8_1
  - pickleshare=0.7.5=py37hc8dfbb8_1001
  - pillow=7.2.0=py37h718be6c_1
  - pip=20.1.1=py_1
  - pixman=0.38.0=h516909a_1003
  - pluggy=0.13.1=py37hc8dfbb8_2
  - poppler=0.87.0=h4190859_1
  - poppler-data=0.4.9=1
  - postgresql=12.2=h8573dbc_1
  - proj=7.0.0=h966b41f_4
  - prometheus_client=0.8.0=pyh9f0ad1d_0
  - prompt-toolkit=3.0.5=py_1
  - prompt_toolkit=3.0.5=1
  - psutil=5.7.0=py37h8f50634_1
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py_1001
  - pycoast=1.4.0=pyh9f0ad1d_0
  - pycodestyle=2.6.0=pyh9f0ad1d_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pyct=0.4.6=py_0
  - pyct-core=0.4.6=py_0
  - pydocstyle=5.0.2=py_0
  - pyepsg=0.4.0=py_0
  - pyflakes=2.2.0=pyh9f0ad1d_0
  - pygments=2.6.1=py_0
  - pykdtree=1.3.1=py37h03ebfcd_1003
  - pylint=2.5.3=py37hc8dfbb8_0
  - pyopenssl=19.1.0=py_1
  - pyorbital=1.6.0=pyh9f0ad1d_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyproj=2.6.1.post1=py37h34dd122_0
  - pyqt=5.12.3=py37h8685d9f_3
  - pyresample=1.16.0=py37h0da4684_0
  - pyrsistent=0.16.0=py37h8f50634_0
  - pyshp=2.1.0=py_0
  - pysocks=1.7.1=py37hc8dfbb8_1
  - pyspectral=0.10.0=pyh9f0ad1d_0
  - python=3.7.6=cpython_h8356626_6
  - python-dateutil=2.8.1=py_0
  - python-geotiepoints=1.2.0=py37h03ebfcd_0
  - python-jsonrpc-server=0.3.4=pyh9f0ad1d_1
  - python-language-server=0.34.1=py37hc8dfbb8_0
  - python_abi=3.7=1_cp37m
  - pytz=2020.1=pyh9f0ad1d_0
  - pyviz_comms=0.7.6=pyh9f0ad1d_0
  - pyxdg=0.26=py_0
  - pyyaml=5.3.1=py37h8f50634_0
  - pyzmq=19.0.1=py37hac76be4_0
  - qdarkstyle=2.8.1=pyh9f0ad1d_0
  - qt=5.12.5=hd8c4c69_1
  - qtawesome=0.7.2=pyh9f0ad1d_0
  - qtconsole=4.7.5=pyh9f0ad1d_0
  - qtpy=1.9.0=py_0
  - rasterio=1.1.5=py37h0492a4a_0
  - readline=8.0=h46ee950_1
  - requests=2.24.0=pyh9f0ad1d_0
  - rope=0.17.0=pyh9f0ad1d_0
  - rtree=0.9.4=py37h8526d28_1
  - satpy=0.22.0=py_0
  - scipy=1.5.0=py37ha3d9a3c_0
  - secretstorage=3.1.2=py37hc8dfbb8_1
  - send2trash=1.5.0=py_0
  - setuptools=49.2.0=py37hc8dfbb8_0
  - shapely=1.7.0=py37hc88ce51_3
  - six=1.15.0=pyh9f0ad1d_0
  - snowballstemmer=2.0.0=py_0
  - snuggs=1.4.7=py_0
  - sortedcontainers=2.2.2=pyh9f0ad1d_0
  - sphinx=3.1.2=py_0
  - sphinxcontrib-applehelp=1.0.2=py_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=1.0.3=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.4=py_0
  - spyder=4.1.4=py37hc8dfbb8_0
  - spyder-kernels=1.9.2=py37hc8dfbb8_0
  - sqlite=3.32.3=hcee41ef_1
  - tbb=2020.1=hc9558a2_0
  - tblib=1.6.0=py_0
  - terminado=0.8.3=py37hc8dfbb8_1
  - testpath=0.4.4=py_0
  - tiledb=1.7.7=h8efa9f0_3
  - tk=8.6.10=hed695b0_0
  - toml=0.10.1=pyh9f0ad1d_0
  - toolz=0.10.0=py_0
  - tornado=6.0.4=py37h8f50634_1
  - tqdm=4.47.0=pyh9f0ad1d_0
  - traitlets=4.3.3=py37hc8dfbb8_1
  - trollimage=1.13.0=py_0
  - trollsift=0.3.4=py_1
  - typed-ast=1.4.1=py37h516909a_0
  - typing_extensions=3.7.4.2=py_0
  - tzcode=2020a=h516909a_0
  - ujson=1.35=py37h3340039_1002
  - urllib3=1.25.9=py_0
  - watchdog=0.10.3=py37hc8dfbb8_0
  - wcwidth=0.2.5=pyh9f0ad1d_0
  - webencodings=0.5.1=py_1
  - wheel=0.34.2=py_1
  - widgetsnbextension=3.5.1=py37hc8dfbb8_1
  - wrapt=1.11.2=py37h8f50634_0
  - wurlitzer=2.0.0=py37hc8dfbb8_1
  - x264=1!152.20180806=h14c3975_0
  - xarray=0.16.0=py_0
  - xerces-c=3.2.2=h8412b87_1004
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.9=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h516909a_0
  - yapf=0.29.0=py_0
  - zarr=2.4.0=py_0
  - zeromq=4.3.2=he1b5a44_2
  - zict=2.0.0=py_0
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h516909a_1006
  - zstd=1.4.4=h6597ccf_3
  - pip:
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
prefix: /home/ghiggi/anaconda3/envs/satpy

