name: spatial
channels:
  - pyviz
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - _tflow_select=2.3.0=mkl
  - abseil-cpp=20200225.2=he1b5a44_2
  - absl-py=0.15.0=pyhd8ed1ab_0
  - affine=2.3.0=py_0
  - aggdraw=1.3.12=py38h6032dad_1
  - aiohttp=3.6.3=py38h7b6447c_0
  - alabaster=0.7.12=py_0
  - aplus=0.11.0=py_1
  - appdirs=1.4.3=py_1
  - argh=0.26.2=pyh9f0ad1d_1002
  - argon2-cffi=20.1.0=py38h1e0a361_1
  - arrow-cpp=1.0.1=py38hbfecb28_14_cpu
  - asciitree=0.3.3=py_2
  - astor=0.8.1=pyh9f0ad1d_0
  - astroid=2.4.2=py38h32f6830_0
  - astropy=4.0.3=py38h1e0a361_0
  - astunparse=1.6.3=pyhd8ed1ab_0
  - async-timeout=3.0.1=py38h06a4308_0
  - async_generator=1.10=py_0
  - atomicwrites=1.4.0=pyh9f0ad1d_0
  - attrs=20.2.0=pyh9f0ad1d_0
  - autopep8=1.5.4=pyh9f0ad1d_0
  - aws-c-common=0.4.59=he1b5a44_0
  - aws-c-event-stream=0.1.6=h84e28f3_5
  - aws-checksums=0.1.9=he252421_2
  - aws-sdk-cpp=1.8.63=h9b98462_0
  - babel=2.8.0=py_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - bleach=3.2.1=pyh9f0ad1d_0
  - blinker=1.4=py_1
  - blosc=1.20.1=he1b5a44_0
  - bokeh=2.2.1=py38h32f6830_0
  - boost-cpp=1.74.0=h9359b55_0
  - boto3=1.15.17=pyh9f0ad1d_0
  - botocore=1.18.17=pyh9f0ad1d_0
  - bqplot=0.12.18=pyh9f0ad1d_0
  - branca=0.3.1=py_0
  - brotli=1.0.9=he1b5a44_2
  - brotlipy=0.7.0=py38h1e0a361_1000
  - brunsli=0.1=he1b5a44_0
  - bzip2=1.0.8=h516909a_3
  - c-ares=1.16.1=h516909a_3
  - ca-certificates=2021.10.8=ha878542_0
  - cached-property=1.5.1=py_0
  - cachetools=4.1.1=py_0
  - cachey=0.2.1=pyh9f0ad1d_0
  - cairo=1.16.0=h3fc0475_1005
  - cartopy=0.18.0=py38h4f3c6b6_2
  - certifi=2021.10.8=py38h578d9bd_1
  - cffi=1.14.3=py38h5bae8af_0
  - cfitsio=3.470=hce51eda_6
  - cftime=1.2.1=py38h8790de6_0
  - chardet=3.0.4=py38h32f6830_1007
  - charls=2.1.0=he1b5a44_2
  - click=7.1.2=pyh9f0ad1d_0
  - click-plugins=1.1.1=py_0
  - cligj=0.5.0=py_0
  - cloudpickle=1.6.0=py_0
  - colorcet=2.0.2=py_0
  - configobj=5.0.6=py_0
  - cryptography=3.1.1=py38h766eaa4_0
  - curl=7.71.1=he644dc0_8
  - cycler=0.10.0=py_2
  - cytoolz=0.11.0=py38h1e0a361_0
  - dask=2.29.0=py_0
  - dask-core=2.29.0=py_0
  - dataclasses=0.8=pyhc8e2a94_3
  - datashader=0.10.0=py_0
  - datashape=0.5.4=py_1
  - dbus=1.13.6=he372182_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - descartes=1.1.0=py_4
  - diff-match-patch=20200713=pyh9f0ad1d_0
  - distributed=2.29.0=py38h32f6830_0
  - docutils=0.16=py38h32f6830_1
  - donfig=0.6.0=pyhd8ed1ab_0
  - entrypoints=0.3=py38h32f6830_1001
  - expat=2.2.9=he1b5a44_2
  - fasteners=0.14.1=py_3
  - fiona=1.8.17=py38h676c6b2_0
  - flake8=3.8.3=py_1
  - fontconfig=2.13.1=h1056068_1002
  - freeglut=3.0.0=hf484d3e_1005
  - freetype=2.10.2=he06d7ca_0
  - freetype-py=2.2.0=pyh9f0ad1d_0
  - freexl=1.0.5=h516909a_1002
  - fsspec=0.8.3=py_0
  - future=0.18.2=py38h32f6830_1
  - gast=0.3.3=py_0
  - gdal=3.1.2=py38hb61cb63_1
  - geopandas=0.8.1=py_0
  - geos=3.8.1=he1b5a44_0
  - geotiff=1.6.0=ha04d9d0_1
  - geoviews=1.8.2=py_0
  - geoviews-core=1.8.2=py_0
  - gettext=0.19.8.1=hc5be6a0_1002
  - gflags=2.2.2=he1b5a44_1004
  - giflib=5.2.1=h516909a_2
  - glib=2.66.1=h680cd38_0
  - glog=0.4.0=h49b9bf7_3
  - google-auth=1.22.1=py_0
  - google-auth-oauthlib=0.4.6=pyhd8ed1ab_0
  - google-pasta=0.2.0=pyh8c360ce_0
  - grpc-cpp=1.32.0=h7997a97_1
  - grpcio=1.31.0=py38hf8bcb03_0
  - gst-plugins-base=1.14.5=h0935bb2_2
  - gstreamer=1.14.5=h36ae1b5_2
  - h5netcdf=0.8.1=py_0
  - h5py=2.10.0=nompi_py38hfb01d0b_104
  - hdf4=4.2.13=hf30be14_1003
  - hdf5=1.10.6=nompi_h3c11f04_101
  - heapdict=1.0.1=py_0
  - holoviews=1.13.4=py_0
  - icu=67.1=he1b5a44_0
  - idna=2.10=pyh9f0ad1d_0
  - imagecodecs=2020.5.30=py38h36e1e94_2
  - imageio=2.9.0=py_0
  - imagesize=1.2.0=py_0
  - importlib-metadata=2.0.0=py38h32f6830_0
  - importlib_metadata=2.0.0=0
  - intervaltree=3.0.2=py_0
  - ipydatawidgets=4.1.0=pyh9f0ad1d_0
  - ipygany=0.4.0=py_0
  - ipykernel=5.3.4=py38h23f93f0_0
  - ipyleaflet=0.13.3=pyh9f0ad1d_0
  - ipympl=0.5.8=pyh9f0ad1d_0
  - ipython=7.18.1=py38h1cdfbd6_0
  - ipython_genutils=0.2.0=py_1
  - ipyvolume=0.6.0a6=pyh9f0ad1d_0
  - ipyvue=1.4.0=pyh9f0ad1d_0
  - ipyvuetify=1.5.1=pyh9f0ad1d_0
  - ipywebrtc=0.5.0=py38h32f6830_1
  - ipywidgets=7.5.1=pyh9f0ad1d_1
  - isodate=0.6.0=py_1
  - isort=5.5.4=py38h32f6830_0
  - jedi=0.17.1=py38h32f6830_0
  - jeepney=0.4.3=py_0
  - jinja2=2.11.2=pyh9f0ad1d_0
  - jmespath=0.10.0=pyh9f0ad1d_0
  - joblib=0.17.0=py_0
  - jpeg=9d=h516909a_0
  - json-c=0.13.1=hbfbb72e_1002
  - jsonschema=3.2.0=py38h32f6830_1
  - jupyter=1.0.0=py_2
  - jupyter_client=6.1.7=py_0
  - jupyter_console=6.2.0=py_0
  - jupyter_core=4.6.3=py38h32f6830_1
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jxrlib=1.1=h516909a_2
  - kealib=1.4.13=h33137a7_1
  - keras-preprocessing=1.1.2=pyhd8ed1ab_0
  - keyring=21.4.0=py38h32f6830_1
  - kiwisolver=1.2.0=py38hbf85e49_0
  - krb5=1.17.1=hfafb76e_3
  - lazy-object-proxy=1.4.3=py38h1e0a361_2
  - lcms2=2.11=hbd6801e_0
  - ld_impl_linux-64=2.35=h769bd43_9
  - lerc=2.2=he1b5a44_0
  - libaec=1.0.4=he1b5a44_1
  - libblas=3.8.0=17_openblas
  - libcblas=3.8.0=17_openblas
  - libclang=10.0.1=default_hde54327_1
  - libcurl=7.71.1=hcdd3856_8
  - libdap4=3.20.6=h1d1bd15_1
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=hcdb4288_2
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-ng=9.3.0=h5dbcf3e_17
  - libgdal=3.1.2=hb2a6f5f_1
  - libgfortran-ng=7.5.0=hae1eefd_17
  - libgfortran4=7.5.0=hae1eefd_17
  - libgomp=9.3.0=h5dbcf3e_17
  - libiconv=1.16=h516909a_0
  - libkml=1.3.0=h74f7ee3_1012
  - liblapack=3.8.0=17_openblas
  - libllvm10=10.0.1=he513fc3_3
  - libnetcdf=4.7.4=nompi_h84807e1_105
  - libnghttp2=1.41.0=h8cfc5f6_2
  - libopenblas=0.3.10=pthreads_hb3c22a3_4
  - libpng=1.6.37=hed695b0_2
  - libpq=12.3=h5513abc_0
  - libprotobuf=3.13.0.1=h8b12597_0
  - libsodium=1.0.18=h516909a_1
  - libspatialindex=1.9.3=he1b5a44_3
  - libspatialite=4.3.0a=h57f1b35_1039
  - libssh2=1.9.0=hab1572f_5
  - libstdcxx-ng=9.3.0=h2ae2ef3_17
  - libthrift=0.13.0=h5aa387f_6
  - libtiff=4.1.0=hc7e4089_6
  - libutf8proc=2.5.0=h516909a_2
  - libuuid=2.32.1=h14c3975_1000
  - libwebp-base=1.1.0=h516909a_3
  - libxcb=1.13=h14c3975_1002
  - libxkbcommon=0.10.0=he1b5a44_0
  - libxml2=2.9.10=h68273f3_2
  - libxslt=1.1.33=h572872d_1
  - libzopfli=1.0.3=he1b5a44_0
  - llvmlite=0.34.0=py38h4f45e52_2
  - locket=0.2.0=py_2
  - lxml=4.5.2=py38hbb43d70_0
  - lz4-c=1.9.2=he1b5a44_3
  - lzo=2.10=h7b6447c_2
  - markdown=3.3=pyh9f0ad1d_0
  - markupsafe=1.1.1=py38h1e0a361_1
  - matplotlib=3.3.2=0
  - matplotlib-base=3.3.2=py38h91b0d89_0
  - mccabe=0.6.1=py_1
  - mistune=0.8.4=py38h1e0a361_1001
  - mock=4.0.2=py_0
  - monotonic=1.5=py_0
  - msgpack-python=1.0.0=py38hbf85e49_1
  - multidict=4.7.6=py38h7b6447c_1
  - multipledispatch=0.6.0=py_0
  - munch=2.5.0=py_0
  - mysql-common=8.0.21=2
  - mysql-libs=8.0.21=hf3661c5_2
  - napari=0.3.6=py_0
  - napari-plugin-engine=0.1.8=py38h32f6830_1
  - napari-svg=0.1.4=py_0
  - nbclient=0.5.0=py_0
  - nbconvert=6.0.7=py38h32f6830_0
  - nbformat=5.0.7=py_0
  - ncurses=6.2=he1b5a44_1
  - nest-asyncio=1.4.1=py_0
  - netcdf4=1.5.4=nompi_py38hec8b9af_102
  - networkx=2.5=py_0
  - notebook=6.1.4=py38h32f6830_0
  - nspr=4.29=he1b5a44_0
  - nss=3.57=he751ad9_0
  - numba=0.51.2=py38hc5bc63f_0
  - numcodecs=0.7.2=py38h950e882_0
  - numexpr=2.7.1=py38hc5bc63f_3
  - numpy=1.19.1=py38hbc27379_2
  - numpydoc=1.1.0=py_1
  - oauthlib=3.1.1=pyhd8ed1ab_0
  - olefile=0.46=py_0
  - openjpeg=2.3.1=h981e76c_3
  - openssl=1.1.1k=h7f98852_0
  - opt_einsum=3.3.0=pyhd8ed1ab_1
  - orc=1.6.5=hd3605a7_0
  - owslib=0.20.0=py_0
  - packaging=20.4=pyh9f0ad1d_0
  - pandas=1.1.2=py38h950e882_0
  - pandoc=2.10.1=h516909a_0
  - pandocfilters=1.4.2=py_1
  - panel=0.9.7=py_0
  - param=1.9.3=py_0
  - parquet-cpp=1.5.1=2
  - parso=0.7.0=pyh9f0ad1d_0
  - partd=1.1.0=py_0
  - pathtools=0.1.2=py_1
  - pcre=8.44=he1b5a44_0
  - pexpect=4.8.0=py38h32f6830_1
  - pickleshare=0.7.5=py38h32f6830_1001
  - pillow=7.2.0=py38h9776b28_1
  - pip=20.2.3=py_0
  - pixman=0.38.0=h516909a_1003
  - pluggy=0.13.1=py38h32f6830_2
  - pooch=1.5.2=pyhd8ed1ab_0
  - poppler=0.89.0=h4190859_1
  - poppler-data=0.4.9=1
  - postgresql=12.3=h8573dbc_0
  - progressbar2=3.53.1=pyh9f0ad1d_0
  - proj=7.1.0=h966b41f_1
  - prometheus_client=0.8.0=pyh9f0ad1d_0
  - prompt-toolkit=3.0.7=py_0
  - prompt_toolkit=3.0.7=0
  - protobuf=3.13.0.1=py38he6710b0_1
  - psutil=5.7.2=py38h1e0a361_0
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py_1001
  - pyarrow=1.0.1=py38h9235441_14_cpu
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycoast=1.5.0=pyhd8ed1ab_0
  - pycodestyle=2.6.0=pyh9f0ad1d_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pyct=0.4.8=py_0
  - pyct-core=0.4.8=py_0
  - pydecorate=0.3.1=py_1
  - pydocstyle=5.1.1=py_0
  - pyepsg=0.4.0=py_0
  - pyflakes=2.2.0=pyh9f0ad1d_0
  - pygments=2.7.1=py_0
  - pyhdf=0.10.2=py38hcc2d4bd_1
  - pyjwt=1.7.1=py_0
  - pykdtree=1.3.1=py38h8790de6_1003
  - pylint=2.6.0=py38h32f6830_0
  - pyopengl=3.1.5=py_0
  - pyopenssl=19.1.0=py_1
  - pyorbital=1.6.0=pyh9f0ad1d_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyproj=2.6.1.post1=py38h8e47818_1
  - pyqt=5.12.3=py38ha8c2ead_3
  - pyresample=1.16.0=py38hc5bc63f_1
  - pyrsistent=0.17.3=py38h1e0a361_0
  - pyshp=2.1.2=pyh9f0ad1d_0
  - pyside2=5.13.2=py38h3b90aee_3
  - pysocks=1.7.1=py38h32f6830_1
  - pyspectral=0.10.5=pyhd8ed1ab_0
  - pytables=3.6.1=py38h1b207d3_2
  - python=3.8.5=h1103e12_9_cpython
  - python-dateutil=2.8.1=py_0
  - python-geotiepoints=1.2.0=py38h8790de6_0
  - python-jsonrpc-server=0.4.0=pyh9f0ad1d_0
  - python-language-server=0.35.1=py_0
  - python-utils=2.4.0=py_0
  - python_abi=3.8=1_cp38
  - pythreejs=2.2.1=pyh9f0ad1d_0
  - pytz=2020.1=pyh9f0ad1d_0
  - pyviz_comms=0.7.6=py_0
  - pywavelets=1.1.1=py38hab2c0dc_2
  - pyxdg=0.26=py_0
  - pyyaml=5.3.1=py38h1e0a361_0
  - pyzmq=19.0.2=py38ha71036d_0
  - qdarkstyle=2.8.1=pyh9f0ad1d_1
  - qt=5.12.9=h1f2b2cb_0
  - qtawesome=1.0.1=pyh9f0ad1d_0
  - qtconsole=4.7.7=pyh9f0ad1d_0
  - qtpy=1.9.0=py_0
  - rasterio=1.1.7=py38h676c6b2_0
  - re2=2020.10.01=he1b5a44_0
  - readline=8.0=he28a2e2_2
  - rechunker=0.4.2=pyhd8ed1ab_0
  - requests=2.24.0=pyh9f0ad1d_0
  - requests-oauthlib=1.3.0=pyh9f0ad1d_0
  - requests-toolbelt=0.9.1=py_0
  - rope=0.17.0=pyh9f0ad1d_0
  - rsa=4.7.2=pyh44b312d_0
  - rtree=0.9.4=py38h08f867b_1
  - s3fs=0.2.2=py_0
  - s3transfer=0.3.3=py38h32f6830_2
  - satpy=0.31.0=pyhd8ed1ab_0
  - scikit-image=0.17.2=py38hc5bc63f_2
  - scikit-learn=0.23.2=py38hee58b96_0
  - scipy=1.5.2=py38h8c5af15_0
  - seaborn=0.11.0=py_0
  - secretstorage=3.1.2=py38h32f6830_1
  - send2trash=1.5.0=py_0
  - setuptools=49.6.0=py38h32f6830_1
  - shapely=1.7.1=py38hc7361b7_0
  - six=1.15.0=pyh9f0ad1d_0
  - snappy=1.1.8=he1b5a44_3
  - snowballstemmer=2.0.0=py_0
  - snuggs=1.4.7=py_0
  - sortedcontainers=2.2.2=pyh9f0ad1d_0
  - sphinx=3.2.1=py_0
  - sphinxcontrib-applehelp=1.0.2=py_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=1.0.3=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.4=py_0
  - spyder=4.1.5=py38h32f6830_0
  - spyder-kernels=1.9.4=py38h32f6830_0
  - sqlite=3.33.0=h4cf870e_0
  - suds-jurko=0.6=py38h32f6830_1003
  - tabulate=0.8.7=pyh9f0ad1d_0
  - tblib=1.6.0=py_0
  - tensorboard=2.7.0=pyhd8ed1ab_0
  - tensorboard-data-server=0.6.0=py38h2b97feb_0
  - tensorboard-plugin-wit=1.8.0=pyh44b312d_0
  - tensorflow=2.2.0=mkl_py38h6d3daf0_0
  - tensorflow-base=2.2.0=mkl_py38h5059a2d_0
  - tensorflow-estimator=2.5.0=pyh81a9013_1
  - termcolor=1.1.0=py_2
  - terminado=0.9.1=py38h32f6830_0
  - testpath=0.4.4=py_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tifffile=2020.10.1=py_0
  - tiledb=2.0.8=h3effe38_1
  - tk=8.6.10=hed695b0_0
  - toml=0.10.1=pyh9f0ad1d_0
  - toolz=0.11.1=py_0
  - tornado=6.0.4=py38h1e0a361_1
  - tqdm=4.50.0=pyh9f0ad1d_0
  - traitlets=4.3.3=py38h32f6830_1
  - traittypes=0.2.1=pyh9f0ad1d_2
  - trollimage=1.14.0=py_0
  - trollsift=0.3.4=py_1
  - typing_extensions=3.7.4.2=py_0
  - tzcode=2020a=h516909a_0
  - ujson=3.2.0=py38h950e882_0
  - urllib3=1.25.10=py_0
  - vaex-arrow=0.5.1=pyh9f0ad1d_0
  - vaex-astro=0.7.0=pyh9f0ad1d_0
  - vaex-core=2.0.3=py38hcb8c335_0
  - vaex-hdf5=0.6.0=pyh9f0ad1d_0
  - vaex-jupyter=0.5.2=pyh9f0ad1d_0
  - vaex-ml=0.10.0=pyh9f0ad1d_0
  - vaex-server=0.3.1=pyh9f0ad1d_0
  - vaex-ui=0.3.0=py_0
  - vaex-viz=0.4.0=pyh9f0ad1d_0
  - vispy=0.6.5=py38h8b2c5b0_1
  - watchdog=0.10.3=py38h32f6830_1
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - werkzeug=2.0.1=pyhd8ed1ab_0
  - wheel=0.35.1=pyh9f0ad1d_0
  - widgetsnbextension=3.5.1=py38h32f6830_1
  - wrapt=1.11.2=py38h1e0a361_0
  - wurlitzer=2.0.0=py38h32f6830_1
  - xarray=0.20.1=pyhd8ed1ab_0
  - xerces-c=3.2.3=hfe33f54_1
  - xorg-fixesproto=5.0=h14c3975_1002
  - xorg-inputproto=2.3.2=h14c3975_1002
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.12=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxfixes=5.0.3=h516909a_1004
  - xorg-libxi=1.7.10=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h516909a_0
  - yapf=0.30.0=pyh9f0ad1d_0
  - yarl=1.6.3=py38h497a2fe_2
  - zarr=2.10.1=pyhd8ed1ab_0
  - zeep=3.4.0=py_0
  - zeromq=4.3.3=he1b5a44_1
  - zfp=0.5.5=he1b5a44_2
  - zict=2.0.0=py_0
  - zipp=3.3.0=py_0
  - zlib=1.2.11=h516909a_1009
  - zstd=1.4.5=h6597ccf_2
  - pip:
    - grid-strategy==0.0.1
    - modapsclient==0.1.1
    - pynndescent==0.5.0
    - pyopengl-accelerate==3.1.5
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
    - tbb==2020.3.254
    - umap-learn==0.5.0
prefix: /home/ghiggi/anaconda3/envs/spatial
