name: gpm_api
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alabaster=0.7.12=py_0
  - alsa-lib=1.2.6.1=h7f98852_0
  - aom=3.4.0=h27087fc_1
  - appdirs=1.4.4=pyh9f0ad1d_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py39hb9d737c_2
  - arrow=1.2.2=pyhd8ed1ab_0
  - asciitree=0.3.3=py_2
  - astroid=2.11.7=py39h06a4308_0
  - asttokens=2.0.5=pyhd8ed1ab_0
  - atomicwrites=1.4.1=pyhd8ed1ab_0
  - attr=2.5.1=h166bdaf_0
  - attrs=22.1.0=pyh71513ae_1
  - autopep8=1.6.0=pyhd8ed1ab_1
  - babel=2.10.3=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.11.1=pyha770c72_0
  - binaryornot=0.4.4=py_1
  - black=22.6.0=pyhd8ed1ab_0
  - bleach=5.0.1=pyhd8ed1ab_0
  - blosc=1.21.1=h83bc5f7_3
  - bokeh=2.4.3=py39hf3d152e_0
  - boost-cpp=1.74.0=h75c5d50_8
  - bottleneck=1.3.5=py39hd257fcd_0
  - branca=0.5.0=pyhd8ed1ab_0
  - brotli=1.0.9=h166bdaf_7
  - brotli-bin=1.0.9=h166bdaf_7
  - brotlipy=0.7.0=py39hb9d737c_1004
  - brunsli=0.1=h9c3ff4c_0
  - build=0.7.0=pyhd8ed1ab_0
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - c-blosc2=2.2.0=h7a311fb_0
  - ca-certificates=2022.6.15=ha878542_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachey=0.2.1=pyh9f0ad1d_0
  - cairo=1.16.0=ha61ee94_1011
  - cartopy=0.20.3=py39hed214b2_1
  - certifi=2022.6.15=py39hf3d152e_0
  - cffi=1.15.1=py39he91dace_0
  - cfitsio=4.1.0=hd9d235c_0
  - chardet=5.0.0=py39hf3d152e_0
  - charls=2.3.4=h9c3ff4c_0
  - charset-normalizer=2.1.0=pyhd8ed1ab_0
  - click=8.1.3=py39hf3d152e_0
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_1
  - cloudpickle=2.1.0=pyhd8ed1ab_0
  - colorama=0.4.5=pyhd8ed1ab_0
  - commonmark=0.9.1=py_0
  - cookiecutter=2.1.1=pyh6c4a22f_0
  - cryptography=37.0.4=py39hd97740a_0
  - curl=7.83.1=h7bff187_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - cytoolz=0.12.0=py39hb9d737c_0
  - dask=2022.7.1=pyhd8ed1ab_0
  - dask-core=2022.7.1=pyhd8ed1ab_0
  - dask-image=2021.12.0=pyhd8ed1ab_0
  - dataclasses=0.8=pyhc8e2a94_3
  - dav1d=1.0.0=h166bdaf_1
  - dbus=1.13.6=h5008d03_3
  - debugpy=1.6.0=py39h5a03fae_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - diff-match-patch=20200713=pyh9f0ad1d_0
  - dill=0.3.5.1=pyhd8ed1ab_0
  - distributed=2022.7.1=pyhd8ed1ab_0
  - docstring_parser=0.13=pyhd8ed1ab_0
  - docutils=0.19=py39hf3d152e_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=0.9.1=pyhd8ed1ab_0
  - expat=2.4.8=h27087fc_0
  - fasteners=0.17.3=pyhd8ed1ab_0
  - ffmpeg=5.1.0=gpl_h2b602b6_100
  - fftw=3.3.10=nompi_h77c792f_102
  - fiona=1.8.21=py39h54775ec_2
  - flake8=4.0.1=pyhd8ed1ab_2
  - flit-core=3.7.1=pyhd8ed1ab_0
  - folium=0.12.1.post1=pyhd8ed1ab_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.0=h8e229c2_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.34.4=py39hb9d737c_0
  - freetype=2.10.4=h0708190_1
  - freetype-py=2.3.0=pyhd8ed1ab_0
  - freexl=1.0.6=h7f98852_0
  - fsspec=2022.7.1=pyhd8ed1ab_0
  - future=0.18.2=py39hf3d152e_5
  - gdal=3.5.1=py39hc691d54_1
  - geopandas=0.11.1=pyhd8ed1ab_0
  - geopandas-base=0.11.1=pyha770c72_0
  - geos=3.11.0=h27087fc_0
  - geotiff=1.7.1=h4fc65e6_3
  - gettext=0.19.8.1=h73d1719_1008
  - giflib=5.2.1=h36c2ea0_2
  - glib=2.72.1=h6239696_0
  - glib-tools=2.72.1=h6239696_0
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.7.6=hf3e180e_5
  - gst-plugins-base=1.20.3=hf6a322e_0
  - gstreamer=1.20.3=hd4edc92_0
  - h5netcdf=1.0.2=pyhd8ed1ab_0
  - h5py=3.7.0=nompi_py39h63b1161_100
  - hdf4=4.2.15=h10796ff_3
  - hdf5=1.12.1=nompi_h2386368_104
  - heapdict=1.0.1=py_0
  - hsluv=5.0.2=pyh44b312d_0
  - icu=70.1=h27087fc_0
  - idna=3.3=pyhd8ed1ab_0
  - imagecodecs=2022.7.31=py39he992b3b_0
  - imageio=2.21.0=pyhfa7a67d_0
  - imageio-ffmpeg=0.4.7=pyhd8ed1ab_0
  - imagesize=1.4.1=pyhd8ed1ab_0
  - importlib-metadata=4.11.4=py39hf3d152e_0
  - importlib_metadata=4.11.4=hd8ed1ab_0
  - importlib_resources=5.9.0=pyhd8ed1ab_0
  - inflection=0.5.1=pyh9f0ad1d_0
  - intervaltree=3.0.2=py_0
  - ipykernel=6.15.1=pyh210e3f2_0
  - ipython=7.33.0=py39hf3d152e_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.7.1=pyhd8ed1ab_0
  - isort=5.10.1=pyhd8ed1ab_0
  - jack=1.9.18=h8c3723f_1002
  - jedi=0.18.1=py39hf3d152e_1
  - jeepney=0.8.0=pyhd8ed1ab_0
  - jellyfish=0.9.0=py39hb9d737c_1
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jinja2-time=0.2.0=pyhd8ed1ab_3
  - joblib=1.1.0=pyhd8ed1ab_0
  - jpeg=9e=h166bdaf_2
  - json-c=0.16=hc379101_0
  - jsonschema=4.9.1=pyhd8ed1ab_0
  - jupyter=1.0.0=py39hf3d152e_7
  - jupyter_client=7.3.4=pyhd8ed1ab_0
  - jupyter_console=6.4.4=pyhd8ed1ab_0
  - jupyter_core=4.11.1=py39hf3d152e_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_widgets=1.1.1=pyhd8ed1ab_0
  - jxrlib=1.1=h7f98852_2
  - kealib=1.4.15=hfe1a663_0
  - keyring=23.7.0=py39hf3d152e_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.4=py39hf939315_0
  - krb5=1.19.3=h3790be6_0
  - lame=3.100=h7f98852_1001
  - lazy-object-proxy=1.7.1=py39hb9d737c_1
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=4.0.0=h27087fc_0
  - libaec=1.0.6=h9c3ff4c_0
  - libavif=0.10.1=h166bdaf_1
  - libblas=3.9.0=15_linux64_openblas
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libcap=2.64=ha37c62d_0
  - libcblas=3.9.0=15_linux64_openblas
  - libclang=14.0.6=default_h2e3cab8_0
  - libclang13=14.0.6=default_h3a83d3e_0
  - libcups=2.3.3=hf5a7f15_1
  - libcurl=7.83.1=h7bff187_0
  - libdap4=3.20.6=hd7c4107_2
  - libdb=6.2.32=h9c3ff4c_0
  - libdeflate=1.12=h166bdaf_0
  - libdrm=2.4.112=h166bdaf_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=h9b69904_4
  - libffi=3.4.2=h7f98852_5
  - libflac=1.3.4=h27087fc_0
  - libgcc-ng=12.1.0=h8d9b700_16
  - libgdal=3.5.1=h32640fd_1
  - libgfortran-ng=12.1.0=h69a702a_16
  - libgfortran5=12.1.0=hdcd56e2_16
  - libglib=2.72.1=h2d90d5f_0
  - libgomp=12.1.0=h8d9b700_16
  - libiconv=1.16=h516909a_0
  - libidn2=2.3.3=h166bdaf_0
  - libkml=1.3.0=h238a007_1014
  - liblapack=3.9.0=15_linux64_openblas
  - libllvm11=11.1.0=hf817b99_3
  - libllvm14=14.0.6=he0ac6c6_0
  - libnetcdf=4.8.1=nompi_h329d8a1_102
  - libnghttp2=1.47.0=h727a467_0
  - libnsl=2.0.0=h7f98852_0
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.20=pthreads_h78a6416_1
  - libopus=1.3.1=h7f98852_1
  - libpciaccess=0.16=h516909a_0
  - libpng=1.6.37=h753d276_3
  - libpq=14.4=hd77ab85_0
  - librttopo=1.1.0=hf730bdb_11
  - libsndfile=1.0.31=h9c3ff4c_1
  - libsodium=1.0.18=h36c2ea0_1
  - libspatialindex=1.9.3=h9c3ff4c_4
  - libspatialite=5.0.1=h38b5f51_18
  - libssh2=1.10.0=ha56f1ee_2
  - libstdcxx-ng=12.1.0=ha89aaad_16
  - libtasn1=4.18.0=h166bdaf_1
  - libtiff=4.4.0=h0d92c0b_2
  - libtool=2.4.6=h9c3ff4c_1008
  - libudev1=249=h166bdaf_4
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.32.1=h7f98852_1000
  - libva=2.15.0=h166bdaf_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libvpx=1.11.0=h9c3ff4c_3
  - libwebp=1.2.3=h522a892_1
  - libwebp-base=1.2.3=h166bdaf_2
  - libxcb=1.13=h7f98852_1004
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.14=h22db469_3
  - libzip=1.9.2=hc869a4a_0
  - libzlib=1.2.12=h166bdaf_2
  - libzopfli=1.0.3=h9c3ff4c_0
  - llvmlite=0.38.1=py39h7d9a04d_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.0.0=py39h029007f_2
  - lz4-c=1.9.3=h9c3ff4c_1
  - magicgui=0.5.1=pyhd8ed1ab_0
  - mapclassify=2.4.3=pyhd8ed1ab_0
  - markupsafe=2.1.1=py39hb9d737c_1
  - matplotlib-base=3.5.2=py39h700656a_1
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mccabe=0.6.1=py_1
  - mistune=0.8.4=py39h3811e60_1005
  - msgpack-python=1.0.4=py39hf939315_0
  - munch=2.5.0=py_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mypy_extensions=0.4.3=py39hf3d152e_5
  - mysql-common=8.0.30=haf5c9bc_0
  - mysql-libs=8.0.30=h28c427c_0
  - napari=0.4.14=pyhd8ed1ab_0
  - napari-console=0.0.4=pyhd8ed1ab_1
  - napari-plugin-engine=0.2.0=pyhd8ed1ab_2
  - napari-svg=0.1.6=pyhd8ed1ab_0
  - nbclient=0.6.6=pyhd8ed1ab_0
  - nbconvert=6.5.0=pyhd8ed1ab_0
  - nbconvert-core=6.5.0=pyhd8ed1ab_0
  - nbconvert-pandoc=6.5.0=pyhd8ed1ab_0
  - nbformat=5.4.0=pyhd8ed1ab_0
  - ncurses=6.3=h27087fc_1
  - nest-asyncio=1.5.5=pyhd8ed1ab_0
  - nettle=3.8.1=hc379101_1
  - networkx=2.8.5=pyhd8ed1ab_0
  - notebook=6.4.12=pyha770c72_0
  - npe2=0.5.2=pyhd8ed1ab_0
  - nspr=4.32=h9c3ff4c_1
  - nss=3.78=h2350873_0
  - numba=0.55.2=py39h66db6d7_0
  - numcodecs=0.10.2=py39h5a03fae_0
  - numpy=1.22.4=py39hc58783e_0
  - numpydoc=1.4.0=pyhd8ed1ab_1
  - openh264=2.2.0=h27087fc_2
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1q=h166bdaf_0
  - p11-kit=0.24.1=hc5aa10d_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.4.3=py39h1832856_0
  - pandoc=2.18=ha770c72_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - partd=1.2.0=pyhd8ed1ab_0
  - pathspec=0.9.0=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - pep517=0.12.0=py39hf3d152e_2
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.2.0=py39hae2aec6_0
  - pims=0.6.1=pyhd8ed1ab_0
  - pint=0.19.2=pyhd8ed1ab_0
  - pip=22.2.2=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=2.5.2=pyhd8ed1ab_1
  - pluggy=1.0.0=py39hf3d152e_3
  - ply=3.11=py_1
  - pooch=1.6.0=pyhd8ed1ab_0
  - poppler=22.04.0=h1434ded_1
  - poppler-data=0.4.11=hd8ed1ab_0
  - portaudio=19.6.0=h57a0ea0_5
  - postgresql=14.4=hfdbbde3_0
  - proj=9.0.1=h93bde94_1
  - prometheus_client=0.14.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.30=pyha770c72_0
  - prompt_toolkit=3.0.30=hd8ed1ab_0
  - psutil=5.9.1=py39hb9d737c_0
  - psygnal=0.3.5=py39hf939315_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pulseaudio=14.0=h7f54b18_8
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycodestyle=2.8.0=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pydantic=1.9.1=py39hb9d737c_0
  - pydocstyle=6.1.1=pyhd8ed1ab_0
  - pyflakes=2.4.0=pyhd8ed1ab_0
  - pygments=2.12.0=pyhd8ed1ab_0
  - pykdtree=1.3.5=py39hd257fcd_0
  - pylint=2.14.5=pyhd8ed1ab_0
  - pyls-spyder=0.4.0=pyhd8ed1ab_0
  - pyopengl=3.1.6=pyhd8ed1ab_1
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyproj=3.3.1=py39hdcf6798_1
  - pyqt=5.15.7=py39h18e9c17_0
  - pyqt5-sip=12.11.0=py39h5a03fae_0
  - pyqtwebengine=5.15.7=py39h18e9c17_0
  - pyrsistent=0.18.1=py39hb9d737c_1
  - pyshp=2.3.1=pyhd8ed1ab_0
  - pysocks=1.7.1=py39hf3d152e_5
  - python=3.9.13=h9a8a25e_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.1=pyhd8ed1ab_0
  - python-lsp-black=1.2.1=pyhd8ed1ab_0
  - python-lsp-jsonrpc=1.0.0=pyhd8ed1ab_0
  - python-lsp-server=1.5.0=pyhd8ed1ab_0
  - python-slugify=6.1.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytomlpp=1.0.11=py39hf939315_0
  - pytoolconfig=1.2.2=pyhd8ed1ab_0
  - pytz=2022.1=pyhd8ed1ab_0
  - pywavelets=1.3.0=py39hd257fcd_1
  - pyxdg=0.28=pyhd8ed1ab_0
  - pyyaml=6.0=py39hb9d737c_4
  - pyzmq=23.2.0=py39headdf64_0
  - qdarkstyle=3.0.3=pyhd8ed1ab_0
  - qstylizer=0.2.1=pyhd8ed1ab_0
  - qt-main=5.15.4=ha5833f6_2
  - qt-webengine=5.15.4=hcbadb6c_3
  - qtawesome=1.1.1=pyhd8ed1ab_0
  - qtconsole=5.3.1=pyhd8ed1ab_0
  - qtconsole-base=5.3.1=pyha770c72_0
  - qtpy=2.1.0=pyhd8ed1ab_0
  - readline=8.1.2=h0f457ee_0
  - requests=2.28.1=pyhd8ed1ab_0
  - rich=12.5.1=pyhd8ed1ab_0
  - rope=1.3.0=pyhd8ed1ab_0
  - rtree=1.0.0=py39hb102c33_1
  - scikit-image=0.19.3=py39h1832856_0
  - scikit-learn=1.1.1=py39h4037b75_0
  - scipy=1.9.0=py39h8ba3f38_0
  - secretstorage=3.3.2=py39hf3d152e_1
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=63.3.0=py39hf3d152e_0
  - shapely=1.8.2=py39h68ae834_3
  - shellingham=1.4.0=pyh44b312d_0
  - sip=6.6.2=py39h5a03fae_0
  - six=1.16.0=pyh6c4a22f_0
  - slicerator=1.1.0=pyhd8ed1ab_0
  - snappy=1.1.9=hbd366e4_1
  - snowballstemmer=2.2.0=pyhd8ed1ab_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - sphinx=5.1.1=pyhd8ed1ab_1
  - sphinxcontrib-applehelp=1.0.2=py_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd8ed1ab_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd8ed1ab_2
  - spyder=5.3.2=py39hf3d152e_0
  - spyder-kernels=2.3.2=py39hf3d152e_0
  - sqlite=3.39.2=h4ff8645_0
  - stack_data=0.3.0=pyhd8ed1ab_0
  - superqt=0.3.3=pyhd8ed1ab_0
  - svt-av1=1.1.0=h27087fc_1
  - tblib=1.7.0=pyhd8ed1ab_0
  - terminado=0.15.0=py39hf3d152e_0
  - text-unidecode=1.3=py_0
  - textdistance=4.3.0=pyhd8ed1ab_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - three-merge=0.1.1=pyh9f0ad1d_0
  - tifffile=2022.7.31=pyhd8ed1ab_0
  - tiledb=2.9.5=h1e4a385_0
  - tinycss2=1.1.1=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tomlkit=0.11.1=pyha770c72_0
  - toolz=0.12.0=pyhd8ed1ab_0
  - tornado=6.1=py39hb9d737c_3
  - tqdm=4.64.0=pyhd8ed1ab_0
  - traitlets=5.3.0=pyhd8ed1ab_0
  - typed-ast=1.5.4=py39hb9d737c_0
  - typer=0.6.1=pyhd8ed1ab_0
  - typing=3.10.0.0=pyhd8ed1ab_0
  - typing-extensions=4.3.0=hd8ed1ab_0
  - typing_extensions=4.3.0=pyha770c72_0
  - tzcode=2022a=h166bdaf_0
  - tzdata=2022a=h191b570_0
  - ujson=5.3.0=py39h5a03fae_0
  - unicodedata2=14.0.0=py39hb9d737c_1
  - unidecode=1.3.4=pyhd8ed1ab_0
  - urllib3=1.26.11=pyhd8ed1ab_0
  - vispy=0.11.0=py39h2afa9b7_0
  - watchdog=2.1.9=py39hf3d152e_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - whatthepatch=1.0.2=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - widgetsnbextension=3.6.1=pyha770c72_0
  - wrapt=1.14.1=py39hb9d737c_0
  - wurlitzer=3.0.2=pyhd8ed1ab_2
  - x264=1!161.3030=h7f98852_1
  - x265=3.5=h924138e_3
  - xarray=2022.6.0=pyhd8ed1ab_1
  - xcb-util=0.4.0=h166bdaf_0
  - xcb-util-image=0.4.0=h166bdaf_0
  - xcb-util-keysyms=0.4.0=h166bdaf_0
  - xcb-util-renderutil=0.3.9=h166bdaf_0
  - xcb-util-wm=0.4.1=h166bdaf_0
  - xerces-c=3.2.3=h55805fa_5
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xyzservices=2022.6.0=pyhd8ed1ab_0
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h7f98852_2
  - yapf=0.32.0=pyhd8ed1ab_0
  - zarr=2.12.0=pyhd8ed1ab_0
  - zeromq=4.3.4=h9c3ff4c_1
  - zfp=0.5.5=h9c3ff4c_8
  - zict=2.2.0=pyhd8ed1ab_0
  - zipp=3.8.1=pyhd8ed1ab_0
  - zlib=1.2.12=h166bdaf_2
  - zlib-ng=2.0.6=h166bdaf_0
  - zstd=1.5.2=h8a70e8d_2
prefix: /home/ghiggi/anaconda3/envs/gpm_api
