name: gpm_api
channels:
  - conda-forge
dependencies:
  - cartopy
  - click
  - donfig
  - dask
  - distributed
  - h5py
  - netcdf4
  - pyresample
  - tqdm
  - trollsift
  - xarray
  - xarray-datatree
  - ximage
  - pycolorbar
  # testing
  - pytest
  - pytest-cov
  - pytest-mock
  - pydantic
